#!/bin/bash
#	Process the columns of cloud_status -m
#
#	$1          $2                      $3                  $4          $5          $6      
#	ID          HOSTNAME                VMTYPE              USER        STATUS      CLUSTER
#
#   States:
#       Unstaged (000000, ignore this one it's never seen),
#       Unpropagated (cccccc)
#       Starting (008000)
#       Running (00ff00)
#       Error (000000)
#       Shutdown (ff00ff, ec2 only)
#
#   The special states for Nimbus:
#       HTTPFail (e9c6af)
#       BrokenPipes (deaa87),
#       Destroyed (d38d5f)
#       NoProxy (c87137)
#       ExpiredProxy (a05a2c)
#       ConnectionRefused (784421)  - most of which are just more specific errors

	declare -i StatusCol=5
	declare -i ClusterCol=6

	PATH=/bin:/usr/bin:/usr/local/bin:/sbin:/usr/sbin:/usr/local/sbin

	if [ "$1" = "config" ]; then
		cloud_status -l | grep -v 8111 | sort | awk \
			'BEGIN{ \
				cloudcount = 0; \
				} \

			{ \
				if ($1=="") next; \
				cloudcount++; \
				clouds[cloudcount] = $1 \
				} \

			END{ \
				for (cloud=1; cloud<=cloudcount; cloud++) { \
					print "multigraph cloud_" clouds[cloud]; \
					print "graph_title Cloud Activity on " clouds[cloud]; \
					print "graph_category Cloud"; \
					print "graph_vlabel Virtual Machines"; \
					print "graph_width 800"; \
					print "graph_height 500\n"; \

					print "error.label Error"; \
					print "error.draw AREA"; \
					print "error.colour 000000"; \
					print "error.max 10000"; \
					print "error.min 0\n"; \

					print "noimage.label NoImage"; \
					print "noimage.draw STACK"; \
					print "noimage.colour 602000"; \
					print "noimage.max 10000"; \
					print "noimage.min 0\n"; \

					print "noproxy.label NoProxy"; \
					print "noproxy.draw STACK"; \
					print "noproxy.colour 605000"; \
					print "noproxy.max 10000"; \
					print "noproxy.min 0\n"; \

					print "unpropagated.label Unpropagated"; \
					print "unpropagated.draw STACK"; \
					print "unpropagated.colour 406040"; \
					print "unpropagated.max 10000"; \
					print "unpropagated.min 0\n"; \

					print "starting.label Starting"; \
					print "starting.draw STACK"; \
					print "starting.colour 008000"; \
					print "starting.max 10000"; \
					print "starting.min 0\n"; \

					print "running.label Running"; \
					print "running.draw STACK"; \
					print "running.colour 00ff00"; \
					print "running.max 10000"; \
					print "running.min 0\n"; \

					print "retiring.label Retiring"; \
					print "retiring.draw STACK"; \
					print "retiring.colour 008888"; \
					print "retiring.max 10000"; \
					print "retiring.min 0\n"; \

					print "heartbeat.label Heartbeat"; \
					print "heartbeat.draw LINE3"; \
					print "heartbeat.colour ff0000\n"; \
					} \
				}'
	else
		cloud_status -m | grep -v 8111 | awk \
			'BEGIN{ \
				cloudcount = 0; \
				while (("cloud_status -l | grep -v 8111 | sort" | getline line)>0) { \
					split(line, words); \
					if (words[1]!="") { \
						cloudcount++; \
						clouds[cloudcount] = words[1] \
						} \
					} \

				switch = "Yes" \
				} \

			/couldn\047t connect/ {switch="No"}; \

			// { \
				if ($0=="" || $1=="ID" || $1=="Total") next; \
				state="error"; \
				if ($'$StatusCol'=="BrokenPipes") state="error"; \
				if ($'$StatusCol'=="ConnectionRefused") state="error"; \
				if ($'$StatusCol'=="Destroyed") state="error"; \
				if ($'$StatusCol'=="HTTPFail") state="noimage"; \
				if ($'$StatusCol'=="NoProxy") state="noproxy"; \
				if ($'$StatusCol'=="ExpiredProxy") state="noproxy"; \
				if ($'$StatusCol'=="Unpropagated") state="unpropagated"; \
				if ($'$StatusCol'=="Starting") state="starting"; \
				if ($'$StatusCol'=="Running") state="running"; \
				if ($'$StatusCol'=="Retiring") state="retiring"; \
				count[$'$ClusterCol',state]++ \
				} \

			END{ \
				for (cloud=1; cloud<=cloudcount; cloud++) { \
					print "multigraph cloud_" clouds[cloud]; \
					print "error.value " count[clouds[cloud],"error"]+0; \
					print "noimage.value " count[clouds[cloud],"noimage"]+0; \
					print "noproxy.value " count[clouds[cloud],"noproxy"]+0; \
					print "unpropagated.value " count[clouds[cloud],"unpropagated"]+0; \
					print "starting.value " count[clouds[cloud],"starting"]+0; \
					print "running.value " count[clouds[cloud],"running"]+0; \
					print "retiring.value " count[clouds[cloud],"retiring"]+0; \

					if (switch=="Yes") print "heartbeat.value 0.0"; \
					print "\n" \
					} \
				}'
	fi
