#!/usr/bin/perl
#	Report jobs by user.
    $option = shift();

    @users = split(/[\s\n]+/, $ENV{'MUNIN_JOBSBYUSER_USERS'});

    @clouds = `cloud_status | awk 'NF>0 && !/^Resource/ && !/^NAME/ {print \$1}' | sort`;
    foreach $cloud (@clouds) {
        chop($cloud);
    }

    if ($option eq 'config') {
        foreach $user (@users) {
            print "multigraph jobs_by_$user\n";
            print "graph_args --lower-limit 0\n";
            print "graph_title HTCondor Jobs by User: $user\n";
            print "graph_category Cloud\n";
            print "graph_vlabel Jobs\n";
            print "graph_width 600\n";
            print "graph_height 300\n\n";

            $areastack='AREA';
            foreach $cloud (@clouds) {
                print "$cloud.label $cloud\n";
                print "$cloud.draw $areastack\n";
                print "$cloud.max 10000\n";
                print "$cloud.min 0\n\n";
                $areastack='STACK';
            }
        }
    } else {
        foreach $user (sort(@users)) {
            foreach $cloud (sort(@clouds)) {
                $count{$user}{$cloud} = 0;
            }
        }

        @vms=`cloud_status -m | awk 'NF>5 && !/^ID/ && !/^Total/ {print \$6 " " \$2}'`;
        foreach $vm (@vms) {
            @x = split(/[\s\n]+/, $vm);
            $cloud{$x[1]}=$x[0];
        }

        @jobs=`condor_q -running  | awk 'NF>5 && !/Submitter:/ && !/RUN_TIME/ {print \$2 " " \$6}'`;
        foreach $job (@jobs) {
            @x = split(/[\s\@\n]+/, $job);
            if ($cloud{$x[2]} eq '') {
                for $cloud (keys(%cloud)) {
                    #print "$x[0] $cloud{$cloud}\n" if $x[2] =~/^$cloud/;
                    $count{$x[0]}{$cloud{$cloud}} += 1 if $x[2] =~/^$cloud/;
                }
            } else {
                #print ">$x[0]< >$cloud{$x[2]}<\n";
                $count{$x[0]}{$cloud{$x[2]}} += 1;
            }
        }

        foreach $user (sort(@users)) {
            print "multigraph jobs_by_$user\n";
            foreach $cloud (sort(@clouds)) {
                print "$cloud.value $count{$user}{$cloud}\n";
            }
        }
    }
