#!/bin/sh
PATH=/bin:/usr/bin:/usr/local/bin:/sbin:/usr/sbin:/usr/local/sbin

if [ "$1" = "config" ]; then

echo 'graph_title UGR Client Requests'
echo 'graph_category Cloud'
echo 'graph_vlabel Requests'
echo 'graph_width 800'
echo 'graph_height 500'
echo 'graph_order requests'
echo 'requests.label Requests'
echo 'requests.draw LINE'
exit 0
fi

count=`grep 'UgrConnector::locate' /var/log/ugr/ugr.log | wc -l`
echo 'requests.value' $count
